// Generated by https://quicktype.io

export type ContentType = 'tv' | 'movie';
export const contentLanguage = {
  en: 'en-US',
  fr: 'fr-FR',
};

type SortOrder = 'asc' | 'desc';
type SortField = 'popularity' | 'release' | 'original_title' | 'vote_average' | 'name' | 'title';

export type SortBy = `${SortField}.${SortOrder}`;
export interface Contents {
  page: number;
  results: ContentResult[];
  total_pages: number;
  total_results: number;
}

type ContentResult = Movie & TvShow;

export interface Content {
  backdrop_path: string;
  genre_ids: number[];
  id: number;
  original_language: string;
  original_title: string;
  overview: string;
  popularity: number;
  poster_path: string;
  vote_average: number;
  vote_count: number;
}
export interface Movie extends Content {
  adult: boolean;
  title: string;
  video: boolean;
  release_date: string;
}
export interface TvShow extends Content {
  name: string;
  first_air_date: string;
}
